HOSTS = {
  :controller => { :hostname => 'controller.local', :ip => '192.168.77.10',   :memory => '512',   :cpu => "1",  :autostart => true},
  :jenkins    => { :hostname => 'jenkins.local',    :ip => '192.168.77.11',   :memory => '5120',  :cpu => "2",  :autostart => true},
  :production => { :hostname => 'production.local', :ip => '192.168.77.12',   :memory => '512',   :cpu => "1",  :autostart => true}
}

$controller_shell = <<SCRIPT

  echo "Running script on Controller"
  apt-get update >/dev/null
  apt-get upgrade -y
  apt-get install software-properties-common -y
  apt-add-repository ppa:ansible/ansible
  apt-get update >/dev/null
  apt-get install ansible zip unzip -y

  echo "Generating ssh keys"
  ssh-keygen -t rsa -N '' -q -f /home/vagrant/.ssh/id_rsa
  cp -f /home/vagrant/.ssh/id_rsa.pub /vagrant/ssh/id_rsa.pub
  cp -f /home/vagrant/.ssh/id_rsa /vagrant/ssh/id_rsa
  cp /vagrant/ssh/config /home/vagrant/.ssh/config
  chmod 600 /home/vagrant/.ssh/config
  cp /vagrant/ssh/git_key /home/vagrant/.ssh/git_key
  chmod 600 /home/vagrant/.ssh/git_key

  echo "Configuring authorized_keys "
  (echo ; cat /vagrant/ssh/id_rsa.pub) >> /home/vagrant/.ssh/authorized_keys
  chmod 640 /home/vagrant/.ssh/authorized_keys

  # bash configuration
  cp /vagrant/bash/bash_profile /home/vagrant/.bash_profile

  # some files might be owned by root, so do this to fix it
  chown vagrant:vagrant /home/vagrant/ -R

  echo "SUCCESS"

SCRIPT

$jenkins_shell = <<SCRIPT

  apt-get update >/dev/null
  apt-get upgrade -y

  echo "Configuring authorized_keys "
  cat /vagrant/ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
  chmod 640 /home/vagrant/.ssh/authorized_keys

  echo "SUCCESS"

SCRIPT

$production_shell = <<SCRIPT

  apt-get update >/dev/null
  apt-get upgrade -y

  echo "Configuring authorized_keys "
  cat /vagrant/ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
  chmod 640 /home/vagrant/.ssh/authorized_keys

  echo "SUCCESS"

SCRIPT

#vagrant plugin install vagrant-hosts --plugin-version=2.9.0
#vagrant plugin install vagrant-share --plugin-version=1.1.9
#vagrant plugin install vagrant-vbguest --plugin-version=0.19.0

# Install additional plugins
required_plugins = %w( vagrant-vbguest vagrant-hosts vagrant-share )
required_plugins.each do |plugin|
  system "vagrant plugin install #{plugin}" unless Vagrant.has_plugin? plugin
end

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  config.vm.synced_folder "../", "/vagrant", owner:"vagrant", mount_options: ["dmode=755,fmode=755"]
  config.vbguest.no_remote = true
  config.vbguest.auto_update = true
  config.ssh.insert_key = true

  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = false
    s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end

	HOSTS.each do |name, host|

		config.vm.define name, autostart: host[:autostart] do |d|
			d.vm.network "private_network", ip: host[:ip]
		  d.vm.provision :hosts, :sync_host => true
			d.vm.hostname = host[:hostname]

      d.vm.provider "virtualbox" do |v|
        v.gui = false
        v.name = host[:hostname]
        v.memory = host[:memory]
        v.cpus = host[:cpu]
				v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	  		v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end

      case name.to_s
        when "controller"
          then d.vm.provision "shell", inline: $controller_shell, privileged: true#, run: "always"
      when "jenkins"
          then d.vm.provision "shell", inline: $jenkins_shell, privileged: true#, run: "always"
      else d.vm.provision "shell", inline: $production_shell, privileged: true#, run: "always"
      end

    end
	end
end
