---
# tasks file for docker
- name: Install Docker prerequisities
  apt:
    name: "{{ packages }}"
    update_cache: true

- name: Add Docker apt gpg key
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
    mode: '0775'

- name: Install Docker
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
  notify: restart docker

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"

- name: Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- name: Docker version
  block:
    - name: Get Docker version
      shell: docker version --format '{{ '{{' }} .Server.Version {{ '}}' }}'
      args:
        executable: /bin/bash
      register: docker_version

    - debug: msg="{{ docker_version.stdout_lines }}"
